### ISSUE TITLE
Some tiles are not drawn properly

### ISSUE THREAD

**Issue by Bravo555** [HopsonCommunity/Community-Game#117]
![screenshot from 2017-04-07 17-02-39](https://cloud.githubusercontent.com/assets/10912424/24806138/294c973a-1bb4-11e7-8702-53197443c109.png)

**Comment by KiddieD** [comment]
Drawn*

**Comment by Bravo555** [comment]
Indeed

**Comment by Bravo555** [comment]
The issue is still unresolved
![obraz](https://cloud.githubusercontent.com/assets/10912424/25136044/33da390c-2454-11e7-9636-bee88ad2df92.png)
