### ISSUE TITLE
A small git tutorial for begginers to explain workflow and encourage best practices

### ISSUE THREAD

**Issue by Bravo555** [HopsonCommunity/Community-Game#131]

**Comment by KiddieD** [comment]
There's lots of tutorials on GIT

**Comment by Bravo555** [comment]
Yeah, but i want to clarify some things in context of this very project and explain why some things are bad.

**Comment by KiddieD** [comment]
We have guidelines for that

**Comment by Bravo555** [comment]
Not all things are in guidelines.

**Comment by Bravo555** [comment]
Git tips are now in [wiki](https://github.com/HopsonCommunity/Community-Game/wiki/Git-tips)
