### ISSUE TITLE
Simplicity is no more

### ISSUE THREAD

**Issue by Esscoder** [HopsonCommunity/Community-Game#166]
Looking at the code, I can guarantee it is no longer beginner friendly. While saddened by this fact, I'm sure you guys have an incredibly good explanation for this and I hope you're engaging the beginners as well as the veterans. Fight on (๑˃̵ᴗ˂̵)و

**Comment by Euxiniar** [comment]
Hey :D
In fact you are right, I am a beginner and I learn a lot of things with this project because it's really complexe. 
But in fact, some guys are working to implement the Entity Component System, to simplify the code. :)

**Comment by Hopson97** [comment]
Hmm, I feel kind of bad for kicking you.

Thing have mostly settled now, and the managers have agreed to unban you if you want to come back?

The main concern is you saying "Do your thing, I will rewrite it later", so please don't do that. :)

https://discord.gg/dEEr9gG

**Comment by Repertoi-e** [comment]
we c zvector u c ban :(

**Comment by KiddieD** [comment]
I wouldn't mind lol
