### ISSUE TITLE
Game smoothness drastically drops when player goes through the walls

### ISSUE THREAD

**Issue by Bravo555** [HopsonCommunity/Community-Game#170]
It's probably the problem with the NPC pathfinding that can't determine the path to the player.

**Comment by kaizi99** [comment]
Its not a bug, its a feature ^^ We just need to readd collisison

**Comment by Bravo555** [comment]
Yeah, but the problem persists. What if we add eg. `noclip` option for testing purposes and disable collision? What if AI simply couldn't find the path because there will be none (closed doors, other NPCs blocking their way)?
