### ISSUE TITLE
Game crashes on launching singleplayer

### ISSUE THREAD

**Issue by Bravo555** [HopsonCommunity/Community-Game#202]
Error log:

> Exception thrown: read access violation.
> 
> this was 0xCDCDCDD5.
> 
> If there is a handler for this exception, the program may be safely continued.

I think we should do some error checking and display a user-friendly message of what happened.  There was a thing that displayed a message box with exception message. Why is it gone?

**Comment by Repertoi-e** [comment]
What platform are you on and can you debug the code to see where it crashes?

**Comment by Bravo555** [comment]
Ah, sorry, forgot about that.
System details:
- OS: Windows 10
- IDE: Microsoft Visual Studio 14 2015

Exception is thrown from `xhash` file, which is the part of standard library.
Does the game crash on linux?

**Comment by Repertoi-e** [comment]
Try commenting zombie add in StatePlaying. Fixes it?

**Comment by Bravo555** [comment]
Yeah

**Comment by Bravo555** [comment]
And I've got another bug.

**Comment by Repertoi-e** [comment]
What is it
