### ISSUE TITLE
Game crashes when player goes outside the map

### ISSUE THREAD

**Issue by Bravo555** [HopsonCommunity/Community-Game#204]
Error message:

> Debug Assertion Failed!
> 
> Program: C:\WINDOWS\SYSTEM32\MSVCP140D.dll
> File: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector
> Line: 1234
> 
> Expression: vector subscript out of range
> 
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts.

Player's position simply cannot be written so an exception is thrown.

**Comment by Repertoi-e** [comment]
It actually is due to not checking if tiles are outside of map when trying to get them. If map width is 100 and you check 101 tile this is the result.

**Comment by Repertoi-e** [comment]
Hence vector subscript out of range

**Comment by Bravo555** [comment]
Yeah, probably your version is more correct since you have been working on it :D

**Comment by Repertoi-e** [comment]
Didn't work on it but stumbled upon it a couple of times while messing with physics :D

**Comment by Bravo555** [comment]
This bug is actually more serious. Game crashes when player collides with the edge of the map too.

**Comment by Repertoi-e** [comment]
It's because it's checking 3x3 area around the player for collision and when you collide you are partially in the wall for a split second and it checks beyond the wall. Gonna implement some bounds checking for getTile method..

**Comment by KiddieD** [comment]
That's cool. Perhaps make it so if it collides with a Border thing, it takes the direction where it collides, and cuts off the to check blocks griddy

**Comment by KiddieD** [comment]
I don't remember closing this

**Comment by Repertoi-e** [comment]
When an issue is closed with a commit and then you accept that commit the issue gets closed from your name.

**Comment by Hopson97** [comment]
Reopen?

**Comment by Repertoi-e** [comment]
It's fixed -,-
